-- ============================================================
-- SPP Portal — Supabase Full Database Schema & Seed
-- Cara Pakai: Copy seluruh teks ini lalu Paste ke 
-- Supabase Dashboard -> SQL Editor -> Run
-- ============================================================

-- 1. Tabel Students (Data Siswa)
CREATE TABLE IF NOT EXISTS public.students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis TEXT UNIQUE,
    nisn TEXT UNIQUE,
    name TEXT NOT NULL,
    parent_wa TEXT NOT NULL,
    kelas TEXT DEFAULT 'X TKR 2',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Payments (Data Pembayaran SPP)
CREATE TABLE IF NOT EXISTS public.payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    proof_file TEXT NOT NULL,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'lunas', 'ditolak')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Users (Manajemen User & Role)
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('admin', 'bendahara', 'wali_kelas', 'orang_tua')),
    kelas TEXT,                                  -- untuk wali_kelas
    student_id BIGINT REFERENCES public.students(id) ON DELETE SET NULL, -- untuk orang_tua
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Notifications (Notifikasi Realtime System)
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,                          -- 'upload', 'approved', 'rejected'
    student_id BIGINT REFERENCES public.students(id) ON DELETE CASCADE,
    payment_id BIGINT REFERENCES public.payments(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    target_role TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Disable Row Level Security (RLS) agar anon key dapat membaca/menulis data publik
ALTER TABLE public.students DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications DISABLE ROW LEVEL SECURITY;

-- 5. Seed Initial Data (User Admin, Bendahara, Wali Kelas)
-- Password default: admin123, bendahara123, walikelas123
INSERT INTO public.users (name, email, password_hash, role, kelas)
VALUES
    ('Administrator', 'admin@spp.sch.id', '$2a$10$7R0Zq8h...placeholder_hash_admin', 'admin', NULL),
    ('Bendahara', 'bendahara@spp.sch.id', '$2a$10$7R0Zq8h...placeholder_hash_bend', 'bendahara', NULL),
    ('Wali Kelas X TKR 2', 'walikelas@spp.sch.id', '$2a$10$7R0Zq8h...placeholder_hash_wali', 'wali_kelas', 'X TKR 2')
ON CONFLICT (email) DO NOTHING;

-- 6. Seed Sample Data Siswa
INSERT INTO public.students (nisn, nis, name, parent_wa, kelas)
VALUES
    ('0081234567', '2024001', 'Ahnaf', '6281234567890', 'X TKR 2'),
    ('0081234568', '2024002', 'Feba', '6281234567891', 'X TKR 2'),
    ('0081234569', '2024003', 'Alfian', '6281234567892', 'X TKR 2')
ON CONFLICT (nisn) DO NOTHING;
